from .account import PlayerAccountUi
from .authentication import PlayerAuthenticationUi
from .bonus import PlayerBonusUi
from .instants import PlayerInstantsUi
from .payments import PlayerPaymentsUi
from .registration import PlayerRegistrationUi
from .draw_games import PlayerDrawGamesUi
from .documents import PlayerDocumentsUi
from .claims import PlayerClaimsUi
