

def create_payload_update_mail(email: str, message_id: str) -> dict:
    payload = {"signature": {"token": "1e0378d768215ef82bcd75918dda8d1b5c6b1c662950fc1d82",
                             "timestamp": "1730986566",
                             "signature": "b66d7febc85b6c15c7dd486b39ada073e9f9a6582764d02a39ddcafed954d4f2",
                             },
               "event-data": {"event": "opened",
                              "id": "UXrg5-cnSD-7H-twO_nH9Q",
                              "timestamp": 1730986666.123456,
                              "flags": {"is-authenticated": True,
                                        "is-routed": False,
                                        "is-big": False,
                                        "is-system-test": False,
                                        "is-test-mode": False,
                                        },
                              "message": {"attachments": [],
                                          "headers": {"message-id": message_id,
                                                      "from": f"Vladimir Karovic <{email}>",
                                                      "to": email,
                                                      "subject": "Black Friday sale is coming!",
                                                      },
                                          "size": 40887,
                                          },
                              "storage": {"key": "BAABAAXxEnKkDdmhQktKuKacl_J9mf-RZg",
                                          "url": "https://storage-us-east4.api.mailgun.net/v3/domains/"
                                                 "web-phoenix-test1.dev.eu-central-1.betware.com/messages/"
                                                 "BAABAAXxEnKkDdmhQktKuKacl_J9mf-RZg",
                                          },
                              "log-level": "info",
                              "recipient": email,
                              "recipient-domain": "pbl.ca",
                              "primary-dkim": "pic._domainkey.web-phoenix-test1.dev.eu-central-1.betware.com",
                              "tags": ["us1:5820f49c-804b-11ec-9b59-fa6d681ae16d",
                                       "72f9b24c-e544-4baf-a7cb-e4e7f3529a2b",
                                       ],
                              "recipient-provider": "Other",
                              "campaigns": [],
                              "delivery-status": {"attempt-no": 1,
                                                  "code": 250,
                                                  "message": "OK",
                                                  "description": "",
                                                  "session-seconds": 2.122,
                                                  "enhanced-code": "",
                                                  "mx-host": "mx01.pbl.ca",
                                                  "tls": True,
                                                  "first-delivery-attempt-seconds": 0.574,
                                                  },
                              "envelope": {"sender": "postmaster@web-phoenix-test1.dev.eu-central-1.betware.com",
                                           "targets": email,
                                           "transport": "smtp",
                                           "sending-ip": "159.135.228.10",
                                           },
                              "user-variables": {"message-id": message_id},
                              "client-info": {"client-name": "string",
                                              "client-type": "string",
                                              "user-agent": "string",
                                              "device-type": "string",
                                              "client-os": "string",
                                              "bot": "string",
                                              },
                              },
               }

    return payload


def create_payload_store_email(email: str, message_id: str) -> dict:
    return {
        "signature": {
            "token": "1e0378d768215ef82bcd75918dda8d1b5c6b1c662950fc1d82",
            "timestamp": "1730986566",
            "signature": "b66d7febc85b6c15c7dd486b39ada073e9f9a6582764d02a39ddcafed954d4f2",
        },
        "event-data": {
            "flags": {
                "is-test-mode": False,
                "is-system-test": False,
                "is-routed": False,
                "is-authenticated": True,
            },
            "envelope": {
                "sender": "noreply@s.playonkansas.com",
                "transport": "smtp",
                "targets": email,
                "sending-ip": "141.193.32.6",
            },
            "campaigns": [],
            "recipient-domain": "pbl.com",
            "event": "delivered",
            "id": "S4_D8C_zRNSANDU-qQObRA",
            "storage": {
                "region": "europe-west1",
                "env": "production",
                "key": "BAABAgUIXYjkui1hfRlIb5YJTlV9V2_lYw",
                "url": "https://storage-europe-west1.api.mailgun.net/v3/domains/"
                       "phoenix-test1.dev.eu-central-1.betware.com/messages/BAABAgUIXYjkui1hfRlIb5YJTlV9V2_lYw",
            },
            "delivery-status": {
                "code": 250,
                "session-seconds": 3.712,
                "enhanced-code": "",
                "mx-host": "mxa-00181202.gslb.pphosted.com",
                "certificate-verified": True,
                "description": "",
                "message": "OK",
                "first-delivery-attempt-seconds": 0.207,
                "attempt-no": 1,
                "tls": True,
            },
            "message": {
                "size": 1197,
                "headers": {
                    "message-id": message_id,
                    "to": f"<{email}>",
                    "subject": "Unable to Create Account",
                    "from": "Kansas Lottery PlayOn® <noreply@s.playonkansas.com>",
                },
                "attachments": [],
            },
            "primary-dkim": "s1._domainkey.phoenix-test1.dev.eu-central-1.betware.com",
            "template": {"name": "headerfooter"},
            "log-level": "info",
            "recipient": email,
            "tags": [],
            "timestamp": 1731600217.7807326,
            "user-variables": {"message-id": message_id},
            "recipient-provider": "Other",
        },
    }


def create_payload_hard_bounce_email(email: str, message_id: str) -> dict:
    return {
        "signature": {
            "token": "1e0378d768215ef82bcd75918dda8d1b5c6b1c662950fc1d82",
            "timestamp": "1730986566",
            "signature": "b66d7febc85b6c15c7dd486b39ada073e9f9a6582764d02a39ddcafed954d4f2",
        },
        "event-data": {
            "event": "failed",
            "id": "UXrg5-cnSD-7H-twO_nH9Q",
            "timestamp": 1730986566.123456,
            "flags": {
                "is-authenticated": True,
                "is-routed": False,
                "is-big": False,
                "is-system-test": False,
                "is-test-mode": False,
            },
            "message": {
                "attachments": [],
                "headers": {
                    "message-id": message_id,
                    "from": f"Dragan Solaja <{email}>",
                    "to": email,
                    "subject": "Black Friday sale is coming!",
                },
                "size": 40887,
            },
            "storage": {
                "key": "BAABAAXxEnKkDdmhQktKuKacl_J9mf-RZg",
                "url": "https://storage-us-east4.api.mailgun.net/v3/domains/"
                       "web-phoenix-test1.dev.eu-central-1.betware.com/messages/BAABAAXxEnKkDdmhQktKuKacl_J9mf-RZg",
            },
            "log-level": "info",
            "recipient": email,
            "recipient-domain": "yopmail.com",
            "primary-dkim": "pic._domainkey.web-phoenix-test1.dev.eu-central-1.betware.com",
            "tags": [
                "us1:5820f49c-804b-11ec-9b59-fa6d681ae16d",
                "72f9b24c-e544-4baf-a7cb-e4e7f3529a2b",
            ],
            "recipient-provider": "Other",
            "campaigns": [],
            "delivery-status": {
                "attempt-no": 1,
                "code": 250,
                "message": "OK",
                "description": "",
                "session-seconds": 2.122,
                "enhanced-code": "",
                "mx-host": "mx01.pbl.ca",
                "tls": True,
                "first-delivery-attempt-seconds": 0.574,
            },
            "envelope": {
                "sender": "postmaster@web-phoenix-test1.dev.eu-central-1.betware.com",
                "targets": email,
                "transport": "smtp",
                "sending-ip": "159.135.228.10",
            },
            "user-variables": {"message-id": message_id},
        },
    }
