name: Scheduled UI Tests

on:
  schedule:
    # Run tests daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  stability-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-suite:
          - tests/ui/registration/test_registration_stability.py
          # Add more test files here as needed
          # - tests/ui/login/test_login_stability.py
          # - tests/ui/payment/test_payment_stability.py
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup test environment
        uses: ./.github/actions/setup-environment

      - name: 🧪 Run stability tests
        id: run-tests
        uses: ./.github/actions/run-ui-tests
        with:
          test-file: ${{ matrix.test-suite }}
          pytest-args: '-v --tb=short -m stability'
        continue-on-error: true

      - name: 📹 Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: stability-test-results-${{ github.run_number }}-${{ strategy.job-index }}
          path: |
            test-results/videos/
            test-results/screenshots/
            test-results/logs/
            test-results/report.html

      - name: 📢 Send Teams notification
        uses: ./.github/actions/teams-notification
        if: always() && (steps.run-tests.outputs.test-result == 'failure' || github.event_name == 'workflow_dispatch')
        with:
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          test-result: ${{ steps.run-tests.outputs.test-result }}
          test-summary: 'Scheduled stability test: ${{ matrix.test-suite }}'
          build-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
